"""empty message

Revision ID: 126ba16c46c2
Revises: 83e9f5631096
Create Date: 2026-01-17 17:24:20.325527

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "126ba16c46c2"
down_revision = "83e9f5631096"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "upload_file",
        sa.Column("id", sa.UUID(), server_default=sa.text("uuid_generate_v4()"), nullable=False),
        sa.Column("account_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), server_default=sa.text("''::character varying"), nullable=False),
        sa.Column("key", sa.String(length=255), server_default=sa.text("''::character varying"), nullable=False),
        sa.Column("size", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("extension", sa.String(length=255), server_default=sa.text("''::character varying"), nullable=False),
        sa.Column("mime_type", sa.String(length=255), server_default=sa.text("''::character varying"), nullable=False),
        sa.Column("hash", sa.String(length=255), server_default=sa.text("''::character varying"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP(0)"), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP(0)"), nullable=False),
        sa.PrimaryKeyConstraint("id", name="pk_upload_file_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("upload_file")
    # ### end Alembic commands ###
