"""empty message

Revision ID: 58716d38aedc
Revises: fb576d868e95
Create Date: 2025-04-04 21:52:54.006684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58716d38aedc'
down_revision = 'fb576d868e95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
