"""empty message

Revision ID: 83e9f5631096
Revises: 58716d38aedc
Create Date: 2025-07-10 19:11:21.917248

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "83e9f5631096"
down_revision = "58716d38aedc"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "api_tool",
        sa.Column("id", sa.UUID(), server_default=sa.text("uuid_generate_v4()"), nullable=False),
        sa.Column("account_id", sa.UUID(), nullable=False),
        sa.Column("provider_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), server_default=sa.text("''::character varying"), nullable=False),
        sa.Column("description", sa.Text(), server_default=sa.text("''::text"), nullable=False),
        sa.Column("url", sa.String(length=255), server_default=sa.text("''::character varying"), nullable=False),
        sa.Column("method", sa.String(length=255), server_default=sa.text("''::character varying"), nullable=False),
        sa.Column(
            "parameters", postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False
        ),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP(0)"), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP(0)"), nullable=False),
        sa.PrimaryKeyConstraint("id", name="pk_api_tool_id"),
    )
    op.create_table(
        "api_tool_provider",
        sa.Column("id", sa.UUID(), server_default=sa.text("uuid_generate_v4()"), nullable=False),
        sa.Column("account_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), server_default=sa.text("''::character varying"), nullable=False),
        sa.Column("icon", sa.String(length=255), server_default=sa.text("''::character varying"), nullable=False),
        sa.Column("description", sa.Text(), server_default=sa.text("''::text"), nullable=False),
        sa.Column("openapi_schema", sa.Text(), server_default=sa.text("''::text"), nullable=False),
        sa.Column(
            "headers", postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False
        ),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP(0)"), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP(0)"), nullable=False),
        sa.PrimaryKeyConstraint("id", name="pk_api_tool_provider_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("api_tool_provider")
    op.drop_table("api_tool")
    # ### end Alembic commands ###
